_format_version: "3.0"
consumers:
- custom_id: dev
  jwt_secrets:
  - algorithm: HS256
    key: trantring
    secret: eDdZEPH455jsrVU0SHl3iaNsXQWLtE3zeRZmLKXvgSU
  username: dev
plugins:
- config:
    credentials: false
    exposed_headers: null
    headers: null
    max_age: null
    methods:
    - GET
    - HEAD
    - PUT
    - PATCH
    - POST
    - DELETE
    - OPTIONS
    - TRACE
    - CONNECT
    origins:
    - '*'
    preflight_continue: false
    private_network: false
  enabled: true
  name: cors
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: delivery-service
  name: delivery-service
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: delivery
    path_handling: v1
    paths:
    - /delivery
    plugins:
    - config:
        anonymous: null
        claims_to_verify: null
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        realm: null
        run_on_preflight: false
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    name: shippers
    path_handling: v1
    paths:
    - /shippers
    plugins:
    - config:
        anonymous: null
        claims_to_verify: null
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        realm: null
        run_on_preflight: false
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: order-service
  name: order-service
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: orders
    path_handling: v1
    paths:
    - /orders
    plugins:
    - config:
        anonymous: null
        claims_to_verify: null
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        realm: null
        run_on_preflight: false
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: restaurant-service
  name: restaurant-service
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - GET
    name: get-restaurant-info
    path_handling: v1
    paths:
    - /restaurant
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    methods:
    - PUT
    - POST
    - PATCH
    - DELETE
    name: restaurant
    path_handling: v1
    paths:
    - /restaurant
    plugins:
    - config:
        anonymous: null
        claims_to_verify: null
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        realm: null
        run_on_preflight: false
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: user-service
  name: user-service
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: auth
    path_handling: v1
    paths:
    - /auth
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  - https_redirect_status_code: 426
    name: users
    path_handling: v1
    paths:
    - /users
    plugins:
    - config:
        anonymous: null
        claims_to_verify: null
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        realm: null
        run_on_preflight: false
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  write_timeout: 60000
